Fix/v3 scrollbars
OHIF/Viewers pull request #2605
Opened 2021-11-05 13:11 UTC by wayfarer3130

Just enable the CSS/HTML class to enable showing the scrollbars on the StudyBrowser thumbnail list

2021-11-16 16:17 UTC, sedghi commented
I deliberately removed it as it was not in the initial design, based on the discussion if you can auto-hide it when mouse is out of the study browser panel, and it only appears if the mouse enters, I don't see why not to merge.

2021-11-16 16:43 UTC, wayfarer3130 commented
> I deliberately removed it as it was not in the initial design, based on the discussion if you can auto-hide it when mouse is out of the study browser panel, and it only appears if the mouse enters, I don't see why not to merge.

The issue is the scroll bar wasn't appearing at all, whether or not the mouse was in the area, so there wasn't a way to scroll many thumbnails.   If you have a CSS rule that shows only when hovering, I'd be fine with that, but that isn't how it works right now.

2021-11-16 18:10 UTC, wayfarer3130 commented on platform/ui/src/assets/styles/styles.css
> +  overflow-y: hidden;
As requested, make this hidden unless hovering.
@sedghi - I did this for both the measurements and the thumbnail area, do you want me to do that just for thumbnails?

2021-12-22 19:40 UTC, sedghi requested changes
The UI has an undesired width change (see video below), I believe you should use [scrollbar-gutter ](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter)

https://user-images.githubusercontent.com/7490180/147146475-56c0563d-a30a-4304-8d7d-c1d842d8fcbf.mp4

)

2021-12-22 22:07 UTC, wayfarer3130 commented
@sedghi  -added the scrollbar gutter as requested.  Also, I moved the scrollbar to the thumbnail level, which keeps the header stable.

2021-12-23 17:11 UTC, sedghi commented
@wayfarer3130 great it works. One of the tests is failing which is for snapshot modal which has a auto-hide scrollbar right now as well.

2022-01-14 15:32 UTC, wayfarer3130 commented
@sedghi  - I fixed the failing test (well, at least locally, still waiting for a CI build).  The problem is a defect in WebKit that doesn't allow scrollIntoView to execute if the overflow is hidden.  I resolved it by making the scrollbars always visible for ohif-scrollbar, and then set them to hide for the thumbnail view.

2022-01-14 20:23 UTC, merged