Add themeable cobbangle to the measurements tools
OHIF/Viewers pull request #2729
Opened 2022-03-02 22:37 UTC by wayfarer3130

This change adds support for a Cobb Angle tool.  The use of the tool can be enabled by including the theme=extraTools parameter on the URL, which loads the configuration settings to add in the cobb angle tool.  There is also documentation added to specify how to change the toolbar menus via configuration.

2022-03-02 22:38 UTC, wayfarer3130 commented
@ladeirarodolfo  - this change is for part of the work we are doing right now, and is tested against the static wado stow rs endpoints.

2022-03-03 16:44 UTC, ladeirarodolfo requested changes

2022-03-03 18:01 UTC, wayfarer3130 commented on platform/viewer/public/config/dicomweb-server.js
> +        wadoUriRoot: 'http://localhost:5984',
This review is against another PR, not the core v3-stable, and this is a revert of a change in the other review.

2022-03-03 18:06 UTC, wayfarer3130 commented on platform/viewer/src/index.js
> +loadSearchConfigPoint(defaultTheme, '/theme', 'theme').then(configsLoaded => {
Yes, adding.

2022-03-03 18:08 UTC, wayfarer3130 commented on platform/viewer/public/config/dicomweb-server.js
> +        imageRendering: 'wadors,wadouri',
Reverting this one.

2022-03-03 18:15 UTC, wayfarer3130 commented on extensions/cornerstone/src/OHIFCornerstoneViewport.js
> +          const viewportProps = { ...props, cine, isPlaying, frameRate, image };
It isn't known whether or not those are being used.  In fact, the default rendering does use them.

2022-03-09 14:04 UTC, wayfarer3130 commented on platform/ui/src/components/ViewportOverlay/index.js
> +  return (props) => {
Fixing

2022-03-09 14:59 UTC, wayfarer3130 commented on platform/ui/src/components/ViewportOverlay/index.js
> +        <div
Thank you, implemented that in the viewport overlay PR.

2022-10-27 18:43 UTC, closed without merging