fixed variant PropTypes is undefined and SeriesNumber type is Number bug
OHIF/Viewers pull request #2793
Opened 2022-05-05 08:37 UTC by 027xiguapi

…mber bug

### PR Checklist

- [ ] Brief description of changes
- [ ] Links to any relevant issues
- [ ] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2022-07-21 22:57 UTC, sedghi commented on platform/viewer/public/config/default.js
> +      sourceName: 'dicomweb', // 接口设置
can you remove this please?

2022-07-21 22:59 UTC, sedghi requested changes
thanks for your PR, please see my comment

2022-08-05 06:58 UTC, 027xiguapi commented
ok，I have solved it

2022-08-05 15:17 UTC, sedghi commented
Can you rebase please?

2022-08-08 00:51 UTC, 027xiguapi commented
Yes, check it

2023-06-19 11:47 UTC, sedghi commented
Hey, thanks for updating it. You can change your based to master since we merged v3-stable to master. Also you need to pull in new updates since we changed the signiture of buttons

2023-09-07 07:33 UTC, closed without merging