Add support for array input for all constraints in HangingProtocolService validator
OHIF/Viewers pull request #3322
Opened 2023-04-12 16:34 UTC by Sofien-Sellami

### Context
This PR updates the validator.js file in the Hanging Protocol Service library to allow  constraints to accept an array of values. Previously, only the contains constraint could accept an array.

### Changes & Results
-Updated functions to accept an array of values.
-Made changes to ensure all constraints accept an array of values for consistency.

### Testing

### Checklist

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: 
- [x] "Node version: 
- [x] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2023-05-26 12:51 UTC, wayfarer3130 commented on platform/core/src/services/HangingProtocolService/lib/validator.js
> +    } else if (JSON.stringify(testValue) === JSON.stringify(value)) {
Ditto about stringify.

2023-05-26 12:54 UTC, wayfarer3130 commented on platform/core/src/services/HangingProtocolService/lib/validator.js
> +validate.validators.includes = function(value, options, key) {
It is unclear to me how includes differs from contains - please add docs if it is different, or delete it if it isn't.

2023-06-01 19:22 UTC, wayfarer3130 commented on platform/core/src/services/HangingProtocolService/lib/validator.js
> + * value = ['abc', 'def', 'GHI']
Does ['abc'] match 'abc' and vice-versa?  That one is probably a use case worth testing because in the DICOM world they are always arrays.

2023-06-01 19:23 UTC, wayfarer3130 commented on platform/core/src/services/HangingProtocolService/lib/validator.js
> + * value = 'Attenuation Corrected' (Fail)
This case should be equivalent to ['Attenuation Corrected'], which should pass if the testValue contains the same identical string.

2023-06-01 19:27 UTC, wayfarer3130 requested changes
Could you add the two edge cases I described - the issue is that for the DICOM library we are using, it converts to/from single item arrays, so on the equals and the other one I commented on,
['abc'] and 'abc'
should be treated equivalently, both for the test value and the original value.

2023-06-06 12:02 UTC, wayfarer3130 commented on platform/docs/docs/platform/extensions/modules/hpModule.md
> +    | equals 	| === 	| All members are === in same order 	| value = ['abc', 'def', 'GHI']<br>testValue = 'abc' (Fail)<br><br>          = ['abc'] (Fail)<br><br>          = ['abc', 'def', 'GHI'] (Valid
I believe the tests are failing on how the `<br>` tag is used - I suspect you need to use <br /> as a closed tag value (XHTML syntax).  Try building hte docs locally to test.

2023-06-06 12:02 UTC, wayfarer3130 requested changes
Will approve as soon as hte build is fixed.

2023-06-13 12:05 UTC, salimkanoun commented
Dear @wayfarer3130 should be good ?

2023-06-29 14:56 UTC, wayfarer3130 approved these changes
Now passing the tests so good to go.

2023-06-29 14:56 UTC, merged