Remove filtered displaySets from parameter from study protocolEngine.findMatch()
OHIF/Viewers pull request #3343
Opened 2023-04-28 15:53 UTC by Sofien-Sellami

### Context
This pull request removes the studyDisplaySets parameter from the protocolEngine.findMatch() call in order to access a list of all expanded displaySets in studyMatchDetails.

### Changes & Results

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [x] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: 
- [x] "Node version: 
- [x] "Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2023-05-26 12:28 UTC, wayfarer3130 commented on platform/core/src/services/HangingProtocolService/HangingProtocolService.ts
> +
Thinking it over, probably leaving displaySets as is, but passing allDisplaySets into the findMatch function would be more consistent.  The rule is testing this study right now, so it should have the display sets for this study, not all display sets, and if a particular rule wants to look at all display sets, then just having it as a another value would make that possible.

2023-05-26 12:30 UTC, wayfarer3130 requested changes
Can you add a hanging protcol example and test set that requires this change to the basic test mode?  
Also, I'd like to see this as an addition to the findMatch rules as opposed to a change to what is currently passed in.  There are use cases this is needed, but having the display sets for the study is used in several existing hanging protocols, which would break them when being used with multi-study display sets.

2023-05-26 13:35 UTC, salimkanoun commented
The change only exposes the displayset at the study matching, at series level display set are only studies display sets. Did the study matching worked some days ? What we understood is that study matching as it was not passing displays set belonging to other studies was probably unable to match any other study outside the current one. (and neither pass other known studies as this.studies in HPservice is now updated to recieve new known studies)

2023-06-02 13:35 UTC, wayfarer3130 commented
Wait till the PR checks pass, then I can merge.

2023-06-13 12:06 UTC, salimkanoun commented
Dear @wayfarer3130 should be good this one too ?

2023-06-29 15:17 UTC, merged