WIP: SCOORD3D point annotations support
OHIF/Viewers pull request #3857
Opened 2023-12-15 19:32 UTC by igoroctaviano

### Context

### Changes & Results

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2023-12-18 19:47 UTC, igoroctaviano commented
@sedghi can you take a look at these changes and let me know what you think? This allows the rendering of scoord3d points by FOR. There's another PR here that is related: https://github.com/cornerstonejs/cornerstone3D/pull/950
I tried to keep the changes to a minimum without impacting existent functioanlity.

2024-02-09 16:35 UTC, mrceresa commented
Hi guys,
very interested on this, which is the current status?

Thanks and regards

2024-02-09 19:06 UTC, igoroctaviano commented
> Hi guys, very interested on this, which is the current status?
> 
> Thanks and regards

@mrceresa This is currently waiting for review. This implementation targeted stack viewports. @sedghi proposed adding the same support to volume viewports instead (natural choice for scoord3ds) but right now the stack version is what we will go with since volume would require a little more effort to implement.

2024-02-21 13:51 UTC, sedghi requested changes
Thanks for the PR, this is not in the right direction I think. Here are my thoughts. 

Based on the requirement, it seems like SCCORD3D should be rendered in any viewport that are in the same FOR and looking at the nearby slice that the annotation is drawn on. 

I believe that is the definition of our volume viewports. You can look at the tmtv which has volume viewports. https://viewer-dev.ohif.org/tmtv?StudyInstanceUIDs=1.3.6.1.4.1.14519.5.2.1.7009.2403.334240657131972136850343327463

![CleanShot 2024-02-21 at 08 48 02](https://github.com/OHIF/Viewers/assets/7490180/851afe43-fdb3-4faa-869b-ecf63b02ed07)

As seen the drawn annotation on the CT is rendering on PT and fusion because of the design of volume viewports (to show annotations if they are nearby, as opposed to stack viewports which needs referencedImageIds). 

So I believe the cornerstony way of implementing this is to 
1. Import SCCORD3D like other regular SCCORDs that we have support 
2. Convert the referenced series into a volume viewport 
3. Force all other viewports that are in the same FOR and share the same normal into volume viewport if mounted
4. Done 

@wayfarer3130 what do you think

2024-03-08 22:24 UTC, fedorov commented
> Convert the referenced series into a volume viewport

@sedghi I think it might be quite beneficial to support these annotations in the stack viewport. If you have a point that is not on the slice plane, you will have to interpolate to the point position. In the acquisitions that are used for prostate MRI you will be dealing with very anisotropic voxel sizes (0.5x0.5x4mm), so if you interpolate, you can get artifacts. And also I think it is very important for clinical workflow to see the point on the original slices.

I think there is significant value in being able to project the point to the closest slice and show it in the stack viewport, with a disclaimer to the user that the point was projected. 

What do you think?

2024-03-11 13:16 UTC, sedghi commented
@fedorov To see the point on the original slices we should use Stack Viewport, but the issue/complexity here is that that annotation needs to be viewed in other series in the same FOR and in the same Slice I guess (no?), how do you imagine handling those without some projection? 

I don't think we interpolate for volume viewports the logic is: if the annotation is within the same slice thickness of **any** viewport, that viewport will show it 

```js
import { vec3 } from 'gl-matrix';
import { CONSTANTS, metaData } from '@cornerstonejs/core';
import type { Types } from '@cornerstonejs/core';
import { Annotations, Annotation } from '../../types';

const { EPSILON } = CONSTANTS;

const PARALLEL_THRESHOLD = 1 - EPSILON;

/**
 * given some `Annotations`, and the slice defined by the camera's normal
 * direction and the spacing in the normal, filter the `Annotations` which
 * is within the slice.
 *
 * @param annotations - Annotations
 * @param camera - The camera
 * @param spacingInNormalDirection - The spacing in the normal direction
 * @returns The filtered `Annotations`.
 */
export default function filterAnnotationsWithinSlice(
  annotations: Annotations,
  camera: Types.ICamera,
  spacingInNormalDirection: number
): Annotations {
  const { viewPlaneNormal } = camera;

  // The reason we use parallel normals instead of actual orientation is that
  // flipped action is done through camera API, so we can't rely on the
  // orientation (viewplaneNormal and viewUp) since even the same image and
  // same slice if flipped will have different orientation, but still rendering
  // the same slice. Instead, we choose to use the parallel normals to filter
  // the annotations and later we fine tune it with the annotation within slice
  // logic down below.
  const annotationsWithParallelNormals = annotations.filter(
    (td: Annotation) => {
      let annotationViewPlaneNormal = td.metadata.viewPlaneNormal;

      if (!annotationViewPlaneNormal) {
        // This code is run to set the annotation view plane normal
        // for historical data which was saved without the normal.
        const { referencedImageId } = td.metadata;
        const { imageOrientationPatient } = metaData.get(
          'imagePlaneModule',
          referencedImageId
        );
        const rowCosineVec = vec3.fromValues(
          imageOrientationPatient[0],
          imageOrientationPatient[1],
          imageOrientationPatient[2]
        );

        const colCosineVec = vec3.fromValues(
          imageOrientationPatient[3],
          imageOrientationPatient[4],
          imageOrientationPatient[5]
        );

        annotationViewPlaneNormal = vec3.create() as Types.Point3;

        vec3.cross(annotationViewPlaneNormal, rowCosineVec, colCosineVec);
        td.metadata.viewPlaneNormal = annotationViewPlaneNormal;
      }
      const isParallel =
        Math.abs(vec3.dot(viewPlaneNormal, annotationViewPlaneNormal)) >
        PARALLEL_THRESHOLD;

      return annotationViewPlaneNormal && isParallel;
    }
  );

  // No in plane annotations.
  if (!annotationsWithParallelNormals.length) {
    return [];
  }

  // Annotation should be within the slice, which means that it should be between
  // camera's focalPoint +/- spacingInNormalDirection.

  const halfSpacingInNormalDirection = spacingInNormalDirection / 2;
  const { focalPoint } = camera;

  const annotationsWithinSlice = [];

  for (const annotation of annotationsWithParallelNormals) {
    const data = annotation.data;
    const point = data.handles.points[0];

    if (!annotation.isVisible) {
      continue;
    }
    // A = point
    // B = focal point
    // P = normal

    // B-A dot P  => Distance in the view direction.
    // this should be less than half the slice distance.

    const dir = vec3.create();

    vec3.sub(dir, focalPoint, point);

    const dot = vec3.dot(dir, viewPlaneNormal);

    if (Math.abs(dot) < halfSpacingInNormalDirection) {
      annotationsWithinSlice.push(annotation);
    }
  }

  return annotationsWithinSlice;
}

```

2024-03-11 14:40 UTC, fedorov commented
> To see the point on the original slices we should use Stack Viewport, but the issue/complexity here is that that annotation needs to be viewed in other series in the same FOR and in the same Slice I guess (no?), how do you imagine handling those without some projection?

The idea is to project, and indicate to the user that the point is not the original one, but has been projected.

> I don't think we interpolate for volume viewports the logic is: if the annotation is within the same slice thickness of any viewport, that viewport will show it

I do not understand the above. "If the annotation is within the same slice thickness of any viewport" - what does this mean?

2024-03-12 13:08 UTC, sedghi commented
maybe we can meet and discuss?

2024-05-28 15:52 UTC, igoroctaviano commented on extensions/cornerstone-dicom-sr/src/viewports/OHIFCornerstoneSRViewport.tsx
> +        isJumpToMeasurementDisabled={false}
The jump was disabled. I just enabled it.

2024-05-28 15:53 UTC, igoroctaviano commented on extensions/cornerstone-dicom-sr/src/enums.js
> +export default enums;
These are SR values so I think they could live in the SR ext.

2024-05-28 15:54 UTC, igoroctaviano commented on extensions/cornerstone-dicom-sr/src/utils/getRenderableData.ts
> +function getRenderableData(GraphicType, GraphicData, ValueType, imageId) {
Refactor + adding scoord3d conditional

2024-05-28 15:57 UTC, igoroctaviano commented on extensions/cornerstone-dicom-sr/src/init.ts
> +  );
Any reason not to use DICOMSRDisplay tool since it knows how to display all value types?

2024-05-28 16:16 UTC, sedghi commented on extensions/cornerstone-dicom-sr/src/getSopClassHandlerModule.ts
> +      measurement.coords.forEach(coord => {
This is a duplication of code in the other file, right?

2024-07-09 20:37 UTC, fedorov commented
@igoroctaviano do we have an instance that can be pointed to a Google DICOM Store to test this functionality?

2024-07-09 20:51 UTC, igoroctaviano commented
@fedorov We don't but you can quickly test it locally using your OIDC config and http://localhost:3000/projects/idc-sandbox-000/locations/us/datasets/idc-dicom-test-inventory/dicomStores/test-samples/study/1.3.6.1.4.1.14519.5.2.1.7310.5101.860473186348887719777907797922. 

In my last discussion with the OHIF team, they mentioned that this PR would need some modifications to be merged, such as adding a new Cornerstone scoord3d point tool and adapter to cornertone instead of using OHIF's DICOM SR display tool. Unfortunately, we don't have the time/resources to implement these changes at this moment.

2024-07-09 21:17 UTC, igoroctaviano commented
> > you can quickly test it locally using your OIDC config
> 
> I am not quite sure what this means. But in any case, since there is no plan to make this available any time soon, and it will be reimplemented anyway, it is not worth it to spend time testing. It is unfortunate that after investing so much into developing this functionality from the IDC side, it is still in this state ...

I agree. The PR got approved at some point but things changed on the OHIF side. I'll leave the PR open since SCOORD3D support might be another project's common interest.

2024-07-09 21:39 UTC, wayfarer3130 commented
Could you test this with the changes for Viewports for Video and WSI?  Much of the same jump to point capabilities were added as a core part of CS3D recently, and then supported in OHIF using the setViewReference capabilities.  I'm not sure how much is still needed, and what other parts are still needed.
The viewport PR is https://github.com/OHIF/Viewers/pull/4182
Could we arrange some time to meet and discuss this?

2024-07-26 16:54 UTC, closed without merging