fix(CustomViewportOverlay): pass accurate data to Custom Viewport Functions
OHIF/Viewers pull request #4224
Opened 2024-06-11 15:48 UTC by Michael-Andersen

### Context

The current CustomViewportOverlay does not provide very useful data to any custom overlay function defined in the config. 

This was discussed in a previous OHIF Office Hours: https://github.com/OHIF/OHIF-Office-Hours/blob/main/notes/2024-06-07.md

### Changes & Results

This change is to provide the current displayed instance(s) if it is in the acquisition plane and a general reference instance for all other viewports. The current instance allows the user to write custom functions which might display particular instance level tags in the acquisition plane viewport such as SliceLocation and the reference instance allows the user to write custom functions which will make use of general tags such as SeriesDescription or ImagePositionPatient. 

### Testing

Here is an example of a custom overlay function you can define in the config to display SliceLocation:

```
cornerstoneOverlayTopRight: {
      id: 'cornerstoneOverlayTopRight',
      items: [
        {
          id: 'InstanceNmber',
          customizationType: 'ohif.overlayItem.instanceNumber',
        },
        {
          id: 'SliceLocation',
          customizationType: 'ohif.overlayItem',
          label: 'Loc:',
          title: 'Slice Location',
          instanceIndex: 0,
          contentF: ({ referenceInstance,
            currentInstance,
            viewportData,
            imageSliceData,
            viewportId,
            instanceNumber, formatters: { formatNumberPrecision } }) =>
            { 
            if (!referenceInstance) {
                              return;
                           }
              var instanceNum;
              if (referenceInstance.ImagePositionPatient == null) {
                return;
              }
              if (viewportId.toLowerCase().includes("fusion")) {
                return;
              }
              if (viewportId.toLowerCase().includes("sagittal")) {
                instanceNum = imageSliceData.imageIndex;
                var res = formatNumberPrecision(referenceInstance.ImagePositionPatient[0] + (referenceInstance.PixelSpacing[0] * instanceNum), 2) + ' mm';
                return res;
              } else if (viewportId.toLowerCase().includes("coronal")) {
                instanceNum = imageSliceData.imageIndex;
                var res = formatNumberPrecision(referenceInstance.ImagePositionPatient[1] + (referenceInstance.PixelSpacing[1] * instanceNum), 2) + ' mm';
                return res;
              } else {
              instanceNum = currentInstance.ImageIndex - 1;
              var res = formatNumberPrecision(currentInstance.SliceLocation, 2) + ' mm';
              return res;
            }},
            }
```

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: Windows 10
- [] Node version: 16.17.0
- [] Browser: Chrome 125.0.6422.142 (Official Build) (64-bit)
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2024-06-11 15:49 UTC, Michael-Andersen commented
@wayfarer3130  As discussed last Thursday in Office Hours

2024-06-14 18:31 UTC, wayfarer3130 commented on extensions/cornerstone/src/Viewport/Overlays/CustomizableViewportOverlay.tsx
> +        currentInstance: instances ? instances.currentInstances[item?.instanceIndex] : null,
instances?.currentInstances[item?.instanceIndex] will avoid the ?: query.

2024-06-14 18:32 UTC, wayfarer3130 commented on extensions/cornerstone/src/Viewport/Overlays/CustomizableViewportOverlay.tsx
> +                  referenceInstance: instances ? instances.referenceInstances[item?.instanceIndex] : null,
You need to get displaySet.instance for the reference instance, since the display set itself determines the reference.

2024-06-14 18:37 UTC, wayfarer3130 commented on extensions/cornerstone/src/services/CornerstoneCacheService/CornerstoneCacheService.ts
> +    const stackImageIds = this._getCornerstoneStackImageIds(displaySet, dataSource).reverse();
This is not a valid way to get the same ordering - in fact, there isn't really a good way of doing it that is equivalent to a "stack"

2024-06-14 19:00 UTC, wayfarer3130 requested changes
Could you update the PR with getting the display set?

2024-06-14 19:00 UTC, wayfarer3130 commented on extensions/cornerstone/src/Viewport/Overlays/CustomizableViewportOverlay.tsx
>    if (viewportData.viewportType === Enums.ViewportType.STACK) {
Replace the code which gets the imageIds with code that gets a display set UID - something like:
const { displaySetInstanceUID } = viewportData?..data?.[0] || {};
if( !displaySetInstanceUID ) return

then get the display set from the response, and return 
{
   displaySet,
   instance: displaySet.instances[instanceIndex],
   referenceInstance: displaySet.instance,
}
and just add that bit right into the properties.

2024-06-21 14:39 UTC, wayfarer3130 commented
I pushed an update to your branch to merge master.  Going to add a couple of changes and then let you look at them.

2024-06-21 16:03 UTC, wayfarer3130 approved these changes
@Michael-Andersen I've made some changes to how this gets things like instances and instance values.  It should be more correct, although that does depend on having the right imageIdIndex value.  It is also easier to customize now since it works with the new customization append fucntionality (although I haven't yet tested that - I might need some small tweaks there).  If you are ok with the changes, I will go ahead and merge it into OHIF.

2024-06-21 16:19 UTC, sedghi commented
@wayfarer3130 Can you please check if these two issues are resolved? if not we fix it in this PR?

https://github.com/OHIF/Viewers/issues/4175
https://github.com/OHIF/Viewers/issues/4168

2024-06-21 19:51 UTC, sedghi commented
This has broken the sorting of the studies https://github.com/OHIF/Viewers/pull/4214

2024-06-21 20:22 UTC, merged