feat: improve dicom tag browswer
OHIF/Viewers pull request #4451
Opened 2024-10-31 21:26 UTC by pedrokohler

### Context

Addresses: https://github.com/OHIF/Viewers/issues/2372

### Changes & Results

Collapse and expand items:

![image](https://github.com/user-attachments/assets/f85ccea8-a619-48db-963d-a486f2ec1ccd)

Deep search:

![image](https://github.com/user-attachments/assets/534cafbf-7b96-410c-b89e-7bef90d6cecb)

Use slider to navigate between series instances:

![image](https://github.com/user-attachments/assets/c4b0023b-1bdd-4b7a-93b7-874c77751a8f)

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2024-10-31 21:32 UTC, pedrokohler commented
@fedorov you can test it here: https://deploy-preview-4451--ohif-dev.netlify.app/

2024-11-01 13:08 UTC, sedghi commented
Can you not touch the top header?

![CleanShot 2024-11-01 at 09 08 25@2x](https://github.com/user-attachments/assets/4a1e1af6-2bf9-45bf-abe4-b32a0eb7293a)

If you can afford not changing that we can merge in 3.9, otherwise it needs to go into the queue for design

2024-11-01 13:10 UTC, sedghi commented
Also noticed that clicking on the (-) doesn't do anything 
![CleanShot 2024-11-01 at 09 09 36@2x](https://github.com/user-attachments/assets/49d42f91-1117-495a-ad41-a173b59e7196)

2024-11-01 13:13 UTC, sedghi requested changes
You're introducing a new UI library (Ant Design) into OHIF, which doesn't align with our planned migration to shadcn/ui tables. I can't merge this until it uses the shadcn/ui table component.

2024-11-01 14:12 UTC, pedrokohler commented
> Also noticed that clicking on the (-) doesn't do anything

It doesn't because you searched for a nested item. In this case it won't. Try without searching and you'll see it works.

2024-11-04 15:55 UTC, IbrahimCSAE reviewed
I like the new change Pedro, it's much better, but like Alireza said, we are using shadcn for all the new components, look at @ohif/ui-next, and https://ui.shadcn.com/, define the components you need in ui-next using shadcn, then import them in the dicom tag browser to build the desired behavior.

2024-11-06 16:18 UTC, sedghi commented
Please revise this PR by tomorrow to include it in 3.9; otherwise, it will be moved to 3.10-beta. Thanks.

2024-11-08 14:09 UTC, pedrokohler commented
> Please revise this PR by tomorrow to include it in 3.9; otherwise, it will be moved to 3.10-beta. Thanks.

I have other priorities right now. This PR will probably have to wait a few weeks, unfortunately.

2025-01-17 16:34 UTC, sedghi commented
<!-- linear:replyTo:2413457136 -->

Any update on this?

2025-01-17 18:31 UTC, pedrokohler commented
Overlapping segmentations will be a priority before I get back to working at this one. And Overlapping Segs is now paused because I'm working on another project for the next couple of weeks.

2025-02-13 15:11 UTC, pedrokohler commented
@sedghi @IbrahimCSAE please check again, I've basically restarted from scratch this time. Now there is no extra lib and I have maintained the virtualization of the table.

2025-02-18 15:29 UTC, sedghi approved these changes
Thank you and the IDC team for this great contribution, as always

2025-02-18 15:29 UTC, merged