Feat/measurements service filtering
OHIF/Viewers pull request #4617
Opened 2024-12-19 15:14 UTC by pedrokohler

### Context

Building on top of: https://github.com/OHIF/Viewers/pull/4501

### Changes & Results

These changes group the measurements of the all-measurements tab by study.

### Testing

### Checklist

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2024-12-23 14:06 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +    }, new Map()) as Map<string, object[]>;
Cant you do new Map<string,object[]> to get the typing right?

2024-12-23 14:27 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +              key={`tracked-${key}`}
entThis isn't necessarily tracked on this version of it, so you shouldn't be referencing tracked here, but should just get something passed in from the parent about what you are naming this.

2025-01-03 15:41 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +        data-cy={'measurements-panel'}
Does this change cause any of the tests to fail?

2025-01-03 16:00 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +  const measurements = displayMeasurements
This grouping function is basically what should be done, but the point is to do it generically with a passed in grouping method so that one can group by study, but also in the future use other grouping methods.   Also, it should be recursive, so that the child grouping items are also using the same group.

2025-01-03 16:01 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
>          {additionalFindings.length > 0 && (
The additional findings are a nested/recursive application of the grouping function - so that this is a sub-group of hte study grouping.

2025-01-03 16:05 UTC, wayfarer3130 commented on extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking.tsx
> +        title="Measurements"
Probably the default grouping function for PanelMeasurements is fine, just passing in the top level selector which selects only tracked measurements, and that should ONLY use series instance UID so that when we add multiple studies to PanelMeasurement it just automatically creates multiple sub-groups.

2025-01-03 16:25 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +  groupBy: string;
Add a method here which creates an array of group items, and assign it the default groupMeasurementsByStudyUID

2025-01-03 16:26 UTC, wayfarer3130 commented
Could you add two additional breakdown to the PanelMeasurements, and change the configuration of PanelMeasurements to use that.  The classes/functions we want are:

groupStudyMeasurement(props, measurements)
   - this is a configurable function that takes the list of measurements and produces a set of grouping items for them, using the props to define any of the grouping methods.
   - the return type is an array of object containing an optional header and a mandatory body, maybe a collapsed body
   - the return instance value creates one array element per study UID found in the measurements, and has an instance of PanelMeasurementGroup as it's default body instance if not configured otherwise in the props
  - For example, it might have   [ {key: studyInstanceUID, body: PanelMeasurementGroup, items: filtered measurements }, ... same sort of item for every study]

Then split the existing primary items/additional items into a separate component that just shows the two items, along with the primary header.

2025-01-03 16:30 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +      const key = displaySet.instances[0].StudyDescription;
Better use the StudyInstanceUID here to make it unique

2025-01-03 16:31 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +        return groupedMeasurements;
Create a grouped measurement object that defines the sub-component to render this on rather than making it a simple list.

2025-01-03 21:27 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +    const key = displaySet.instances[0].StudyDescription;
Use StudyInstanceUID

2025-01-04 15:38 UTC, pedrokohler commented on extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking.tsx
> +        title="Measurements"
Filtering measurements to include only tracked ones is understandable—that makes sense.

However, I don’t understand why, or even what it means, to 'group' measurements by 'tracked measurements.' Could you clarify?

2025-01-06 12:22 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +  const defaultGroupingFunction = groupByStudy(displaySetService);
I think you should assume that any other grouping function might also need services and/or commands managers.  If you do it this way, then you can setup the grouping function appropriately:
const groupingFunction = (groupingFunctionConstructor || groupByStudyConstructor)(props)
where props is the props to the panel measurement table.

2025-01-06 12:30 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
>    measurementFilters = { measurementFilter: filterAny },
Could you fix this type - make it just pass in measurementFilter, it doesn't need to be multiple instances here.

2025-01-06 12:31 UTC, wayfarer3130 commented on extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking.tsx
>        updatedMeasurementFilters.measurementFilter = filterTracked(trackedStudy, trackedSeries);
Can you fix the measurementFilter to be just a single filter, and make it independent of the tracked study.

2025-01-06 12:34 UTC, wayfarer3130 commented on extensions/measurement-tracking/src/panels/PanelMeasurementTableTracking.tsx
> +                  commandsManager.runCommand('clearMeasurements', measurementFilters);
Ouch - this one is running clear measurements instead of saveCSV - can you fix that so it runs saveCSV (or whatever the command name is to save the CSV)
Also, can you pass in the nested measurement filter instead of the top level measurement filter for all 3 commands - that is the new filter I (just) asked to be created in the PanelMeasurement table - that way the command applies to the correct set of data.

2025-01-06 12:36 UTC, wayfarer3130 commented on platform/core/src/utils/measurementGroupings.ts
> +export const groupByStudy = displaySetService => (groupedMeasurements, item) => {
Just add a docs to indicate that this groups measurements by study in order to allow display and saving by study.

2025-01-06 12:38 UTC, wayfarer3130 requested changes
very close now, I did notice one bug that had been previously introduced (probably by me) that needs fixing, and another issue that would only occur if we enabled multiple study tracking.

2025-01-13 14:36 UTC, sedghi commented
Can you please revisit this PR since the parent PR is merged? Thanks

2025-01-14 13:44 UTC, wayfarer3130 commented on extensions/cornerstone/src/getPanelModule.tsx
> +      label: 'All Measurements',
Can you revert this change - it was somethign Alireza didn't want.

2025-01-14 13:46 UTC, wayfarer3130 commented on extensions/cornerstone/src/panels/PanelMeasurement.tsx
> +                <></>
null can returned here

2025-01-14 13:49 UTC, wayfarer3130 approved these changes
These changes are a good base for the grouping of measurements

2025-01-14 13:56 UTC, wayfarer3130 approved these changes
It looks nice to be able to have the additional studies grouping.

2025-01-14 13:57 UTC, merged