ui(component): Tooltip component enhanced
OHIF/Viewers pull request #4635
Opened 2024-12-30 20:33 UTC by dan-rukas

### Context

Updated the `tooltip` component in ui-next to include an optional copy action button. This replaces the previous `TooltipClipboard` legacy component. Behavior for "copy" is simplified to a "done" icon and does not remove the tooltip text like the legacy component (see image below).

Updated previous legacy `Tooltip` and `TooltipClipboard` components in the Application to use `Tooltip` in ui-next in multiple locations in the App (see below).

Visual examples:
![Tooltip-enhanced](https://github.com/user-attachments/assets/06b1d05d-e320-4250-9819-95e2e114d011)

### Changes & Results

### Testing

### Checklist

#### PR

- [✅] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [✅] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] No documentation updates. Component library will be updated after a more complete migration of legacy components.

#### Tested Environment

- [✅] OS: macOS Sequoia 15.2, Apple M4 Pro
- [] Node version: v23.5.0
- [] Browser: Chrome 131.0.6778.205 (Official Build) (arm64)
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

2025-01-03 15:27 UTC, IbrahimCSAE requested changes

2025-01-03 15:27 UTC, IbrahimCSAE commented on platform/ui/src/components/ToolbarButton/ToolbarButton.tsx
> -  const toolTipClassNameToUse =
why did we remove this? we need it to size the buttons dynamically for the toolbox in the segmentation panel vs the buttons in the toolbar, if you take a look now you will notice that its broken

2025-01-03 15:27 UTC, IbrahimCSAE commented on platform/ui/src/components/ToolbarButton/ToolbarButton.tsx
> -      <Tooltip
the logic of showing a dropdown content was used by the grid layout tool, now the grid layout tool is behaving in-correctly, it looks like if you hover on it the content will show as a tooltip, but clicking on it does nothing anymore.

We need it to have a tooltip like all other buttons, but clicking on it still brings the dropdown content (layout selector)

2025-01-08 18:10 UTC, sedghi approved these changes

2025-01-08 18:10 UTC, merged